--TESTES
SELECT CADASTRAR_CLIENTE(100, 'Ana Silva', 'Rua das Flores, 123', '11999990001', 'ana@email.com'); 
-- TESTE REALIZADO COM SUCESSO, FOI VALIDO!

SELECT CADASTRAR_CLIENTE(100, 'João Santos', 'Av. Paulista, 456', '11999990002', 'joao@email.com');
--COM SUCESSO ID JA EXISTE!

SELECT CADASTRAR_CLIENTE(101, 'Maria Oliveira', 'Rua das Acácias, 789', '11999990003', 'email-invalido');
--COM SUCESSO, EMAIL INVALIDO!

SELECT CADASTRAR_FUNCIONARIO(50, 'Carlos Oliveira', '12345', 'carlos@floricultura.com', 'Vendedor');
-- COM SUCESSO, O TELEFONE DEU ERRADO POR SER INVÁLIDO!

SELECT CADASTRAR_PRODUTO(90, 10, 'Vaso de Rosas', 49.90, 'Arranjo', NULL);
-- COM SUCESSO, CADASTRO EFETUADO!

SELECT CADASTRAR_PRODUTO(90, 20, 'Rosas Vermelhas', 9.90, 'Flor', 1);
-- COM SUCESSO, EMITE O ERRO DUPLICADO!

SELECT CADASTRAR_PRODUTO(3, 15, 'Vaso Decorativo', 29.90, 'Vaso', 1);
-- COM SUCESSO, ISSO SIGNIFICA QUE O PRODUTO AO QUAL TENTO INSERIR TEM UM COMPONENTE INVÁLIDO! JA EXISTE.

SELECT CADASTRAR_CLIENTE(103, 'Maria Oliveira', 'Rua dos Lírios, 789', '11999990003', 'maria@email.com');
--CADASTREI, COM SUCESSO!
SELECT CADASTRAR_FUNCIONARIO(63, 'Fernanda Costa', '11999990004', 'fernanda@floricultura.com', 'Atendente');
-- CADASTREI!
SELECT REGISTRAR_PEDIDO(212, 102, '11999990003', 51, 1, 2, 49.90);
-- COM SUCESSO!
SELECT REMOVER_CLIENTE(102);
-- DEU ERRO

-- testes 25/06
INSERT INTO PEDIDO (ID_PEDIDO, ID_CLIENTE, TELEFONE, TOTAL, ID_FUNCIONARIO)
VALUES (14, 14, '86999990014', 0, 4);
INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANT) 
VALUES (14, 1, 5);
SELECT * FROM ITEM_PEDIDO WHERE ID_PEDIDO = 14;
--  COM SUCESSO! .. retornou o registro do item do pedido com VALOR_UNITARIO = 9.90

SELECT TOTAL FROM PEDIDO WHERE ID_PEDIDO = 14;
-- COM SUCESSO, CALCULOU!

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANT) 
VALUES (14, 2, 2); 
--INSERINDO SEGUNDO ITEM
SELECT TOTAL FROM PEDIDO WHERE ID_PEDIDO = 14;

SELECT CADASTRAR_DADO(
    'CLIENTE',
    'ID_CLIENTE, NOME, ENDERECO, TELEFONE, EMAIL',
    '25, ''Maria Oliveira'', ''Av. Principal, 456'', ''9876-5432'', ''maria.o@email.com'''
);

SELECT * FROM PRODUTOS_BAIXO_ESTOQUE(10);
--DEU CERTO
SELECT * FROM PRODUTOS_MAIS_VENDIDOS(5);
--DEU CERTO
SELECT * FROM VENDAS_POR_FUNCIONARIO();
--DEU CERTO
SELECT VERIFICAR_ESTOQUE_COMPOSICAO(3);
-- DEU CERTO!
SELECT MONTAR_PRODUTO_COMPOSTO(3, 2);
-- RETUN VOID
SELECT ESTOQUE FROM PRODUTO WHERE ID_PRODUTO = 1;
--REDUZIU 4 UNIDADES
SELECT ESTOQUE FROM PRODUTO WHERE ID_PRODUTO = 3;
-- AUMENTOU 2 UND


SELECT REMOVER_DADO(
    'CLIENTE',
    'ID_CLIENTE',
    '25'
	-- '25' é uma string, mesmo que ID_CLIENTE seja um INT.
);

SELECT ALTERAR_DADO(
    'CLIENTE',
    'ID_CLIENTE',
    '24',
    'ENDERECO = ''Nova Rua, 789'', TELEFONE = ''9999-1111'''
);
