-- TABELA CLIENTE
CREATE TABLE CLIENTE (
  ID_CLIENTE INT PRIMARY KEY,
  NOME VARCHAR(100),
  ENDERECO VARCHAR(200),
  TELEFONE VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO (
  ID_FUNCIONARIO INT PRIMARY KEY,
  NOME VARCHAR(100),
  TELEFONE VARCHAR(20),
  EMAIL VARCHAR(100),
  CARGO VARCHAR(50)
);

-- TABELA FORNECEDOR
CREATE TABLE FORNECEDOR (
  ID_FORNECEDOR INT PRIMARY KEY,
  NOME VARCHAR(100),
  TELEFONE VARCHAR(20),
  EMAIL VARCHAR(100)
);

-- TABELA PRODUTO
CREATE TABLE PRODUTO (
  ID_PRODUTO INT PRIMARY KEY,
  ESTOQUE INT,
  NOME VARCHAR(100),
  PRECO DECIMAL(10,2),
  TIPO VARCHAR(50),
  ID_PRODUTO_COMPOE INT,
  FOREIGN KEY (ID_PRODUTO_COMPOE) REFERENCES PRODUTO(ID_PRODUTO)
);

-- TABELA PEDIDO
CREATE TABLE PEDIDO (
  ID_PEDIDO INT PRIMARY KEY,
  ID_CLIENTE INT,
  TELEFONE VARCHAR(20),
  TOTAL DECIMAL(10,2),
  ID_FUNCIONARIO INT,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

-- RELACIONAMENTO ITEM_PEDIDO
CREATE TABLE ITEM_PEDIDO (
  ID_ITEM_PEDIDO SERIAL PRIMARY KEY,
  ID_PEDIDO INT,
  ID_PRODUTO INT,
  QUANT INT,
  VALOR_UNITARIO DECIMAL(10,2),
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- TABELA COMPRA
CREATE TABLE COMPRA (
  ID_COMPRA INT PRIMARY KEY,
  ID_FORNECEDOR INT,
  DATA DATE,
  TOTAL DECIMAL(10,2),
  ID_FUNCIONARIO INT,
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR),
  FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

-- RELACIONAMENTO ITEM_COMPRA
CREATE TABLE ITEM_COMPRA (
  ID_ITEM_COMPRA SERIAL PRIMARY KEY,
  ID_COMPRA INT,
  ID_PRODUTO INT,
  QUANT INT,
  VALOR_UNITARIO DECIMAL(10,2),
  FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- RELACIONAMENTO COMPOSICAO_PRONTA
CREATE TABLE COMPOSICAO_PRONTA(
ID_PROD_COMP1 INT NOT NULL,
ID_PROD_COMP2 INT NOT NULL,
QUANT INT NOT NULL,
FOREIGN KEY (ID_PROD_COMP1) REFERENCES PRODUTO(ID_PRODUTO),
FOREIGN KEY (ID_PROD_COMP2) REFERENCES PRODUTO(ID_PRODUTO)
);
